---
title: "Explore number of genes seen in each cell"
author: "Briana Mittleman"
date: 2017-03-07
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

<!-- Add your analysis here -->


```{r data}
#input molecule (pre-filter)
molecules <- read.table("../../singleCellSeq/data/molecules.txt", header = TRUE, stringsAsFactors = FALSE)
dim(molecules)
```


Count number of genes seen in each individual cell  

```{r count non zero}
num_genes= colSums(molecules!= 0)
```

```{r save, eval=FALSE}
save(num_genes, file="../data/num_genes.Rda")
```


Vizualize this:  

```{r}
hist(num_genes,  xlab="Number of genes", main="Number of genes seen per cell")
boxplot(num_genes)
```


###Exclude bad quality cells

```{r}
#load quality single cells 
quality_single_cells <- scan("../../singleCellSeq/data/quality-single-cells.txt", what = "character")

molecules_quality=molecules[, colnames(molecules) %in% quality_single_cells]
dim(molecules_quality)
```

Count number of genes seen in each individual cell  

```{r count genes quality}
num_genes_qual= colSums(molecules_quality!= 0)
```

```{r save qual, eval=FALSE}
save(num_genes_qual, file="../data/num_genes_qual.Rda")
```




vizualize:  

```{r}
hist(num_genes_qual, xlab="Number of genes", main="Number of genes seen per high quality cell")
boxplot(num_genes_qual)
```
